name: Infobip GitHub Actions

# Triggers the workflow on push events but only for the master branch.
on:
  push:
    branches: [ master ]

# Runs the main job which will eventually publish the new version of Docker image
# containing runnable code example on the DockerHub.
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Set up QEMU, a generic and open source machine emulator and virtualizer.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # Set up Docker Buildx, a CLI plugin that extends the docker command with
      # the additional features of builder toolkit.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Performs the login to the DockerHub using GitHub repository secrets.
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Builds the latest version of the Docker image and pushes it to the DockerHub.
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: infobip/${{ github.event.repository.name }}:latest
